version: '3.4'

services:
  backend:
    image: backend
    build: ./backend
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
  
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - 3000:3000
  
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./backend/database/data:/data/db
